### ISSUE TITLE
💡 Create a thread just for post with picture

### ISSUE THREAD

**Issue by NicolasQuenon** [MarcusOtter/discord-needle#233] opened 2022-07-24 14:18 UTC
### Describe the improvement

Hi ! I would like create an auto-thread just for the post with picture (for comments for example). Do you need this feature also? Could you add it ? 
Thanks

### Problems this improvement solves

Too much auto-thread are created for nothing.

**Comment by MarcusOtter** [comment] 2022-07-24 14:22
Duplicate of #93

**Closed by MarcusOtter** 2022-07-24 14:22 UTC
Labels: improvement 💡
