### ISSUE TITLE
💡 Blacklist and Whitelist for roles and users

### ISSUE THREAD

**Issue by afgks** [MarcusOtter/discord-needle#270] opened 2022-08-28 00:47 UTC
### Describe the improvement

The title says it all. Please add a Blacklist and Whitelist functionality for roles and users. So we can include/exclude certain roles/users from creating threads automatically.

### Problems this improvement solves

In my use case, bots used for moderation like Dyno and YAGPDB will post messages in the channel when we do moderations there, which will trigger the bot to make new threads. We don't want that.

I can also imagine that in some use cases admins might want to whistlist only one or two roles to make new threads, without barring other people from posting in the channel.

### Alternative solutions

N/A

**Comment by MarcusOtter** [comment] 2022-08-28 00:49
Duplicate of #93

**Closed by MarcusOtter** 2022-08-28 00:49 UTC
Labels: improvement 💡
