### ISSUE TITLE
💡 auto-adds

### ISSUE THREAD

**Issue by tntgav** [MarcusOtter/discord-needle#171] opened 2022-05-26 07:58 UTC
### Describe the improvement

hopefully simple thing, be able to auto-add specific members in every thread that is auto created.

### Problems this improvement solves

this solves the solution of having other bots that need to be in the thread that are not automatically joining on their own. especially useful for moderating servers.

**Comment by MarcusOtter** [comment] 2022-05-26 12:54
Duplicate of #52

**Closed by MarcusOtter** 2022-05-26 12:54 UTC
Labels: duplicate 👉
