### ISSUE TITLE
💡 Automatically set thread title to the first few words of the message

### ISSUE THREAD

**Issue by phenomen** [MarcusOtter/discord-needle#145] opened 2022-04-29 20:44 UTC
### Describe the improvement

As an option, I would like to see a title to be automatically set to the first 5 words of the message that initiated a thread creation.

### Problems this improvement solves

Right now, threads have very non-descriptive titles by default (username). It makes it difficult to navigate through threads since I do not know the context of the thread.

**Comment by MarcusOtter** [comment] 2022-05-01 17:41
Duplicate of #29

**Closed by MarcusOtter** 2022-05-01 17:41 UTC
Labels: duplicate 👉
