### ISSUE TITLE
Auto-name thread based on Initial post

### ISSUE THREAD

**Issue by itsdinkd** [MarcusOtter/discord-needle#149] opened 2022-05-08 18:45 UTC
### Describe the improvement

I believe having the option to auto-name threads based on certain standards would be beneficial to not only staff, but also to other people looking to skim through the support channel, or whatever channel you use for auto-thread. 

Instead of having the thread name being **Username (Date)** with auto-name it can be **Looking to see how to run etc etc etc etc*

### Problems this improvement solves

Easier readability when skimming the channel, and helps with channel list

### Alternative solutions

Manually using /title to change the thread name. this can be an issue when you have a large discord

**Comment by MarcusOtter** [comment] 2022-05-09 09:34
Duplicate of #29

**Closed by MarcusOtter** 2022-05-09 09:34 UTC
Labels: improvement 💡
