### ISSUE TITLE
💡 Auto-thread after x replies setting

### ISSUE THREAD

**Issue by auwsom** [MarcusOtter/discord-needle#434] opened 2023-05-23 23:30 UTC
### Describe the improvement

Hi there, I just found this tool and I think its great! Maybe I haven't used it enough, but I was thinking it would create a thread automatically, not after every message, but after two users started talking back and forth (maybe two times). 

I dont think every message needs a thread, but when a two users start talking back and forth, it can detract from the communication in a Channel. (This is like how in SE after a few back and forths in the comments there is a bot recommending the discussion be moved to a chat). Since this exists in SE, it seems doable. I would suggest by default it happens after say 2 "back-and-forths" (or 4 messages between 2 users without one from a 3rd user). Either metric could work.. maybe the one in parenthesis would be most clear.. it could apply to direct replies or just @'s between 2 users. And there could be a setting to adjust the threshold for different communities.

### Problems this improvement solves

It solves having thread for messages when they aren't desired.

**Comment by MarcusOtter** [comment] 2023-05-23 23:32
Thank you for the suggestion, this has been suggested here: https://github.com/MarcusOtter/discord-needle/issues/93#issuecomment-1067759096

Closing this as a duplicate!

**Comment by MarcusOtter** [comment] 2023-05-23 23:32
Duplicate of #93

**Closed by MarcusOtter** 2023-05-23 23:32 UTC
Labels: improvement 💡

**Comment by auwsom** [comment] 2023-05-23 23:34
@MarcusOtter thanks.. i did search for previous issues, but didnt see it in the 2 pages I scrolled through.
