### ISSUE TITLE
💡 Lock thread

### ISSUE THREAD

**Issue by ririko5834** [MarcusOtter/discord-needle#285] opened 2022-09-01 09:31 UTC
### Describe the improvement

Add command and button (optional) to lock/close thread as moderator. Those should be only used by moderators

**Comment by MarcusOtter** [comment] 2022-09-01 09:35
Duplicate of https://github.com/MarcusOtter/discord-needle/issues/44 (it's yours 😄)

**Closed by MarcusOtter** 2022-09-01 09:35 UTC
Labels: improvement 💡
