### ISSUE TITLE
💡 Lock threads

### ISSUE THREAD

**Issue by mnkrome** [MarcusOtter/discord-needle#342] opened 2022-11-01 13:57 UTC
### Describe the improvement

Add an option so the Close command closes and locks the thread; instead of just close it.

### Problems this improvement solves

Sometimes mods want the thread  to be close permanently so people can't comment anymore; I think that option would be very useful so the mods doesn't have to go and make the change manually.

**Comment by MarcusOtter** [comment] 2022-11-01 14:21
Duplicate of #44

**Closed by MarcusOtter** 2022-11-01 14:21 UTC
Labels: improvement 💡
