### ISSUE TITLE
💡 Add possibility to override auto-thread creation behavior. E.g. when message starts with some specific regex configurable part.

### ISSUE THREAD

**Issue by gliter** [MarcusOtter/discord-needle#459] opened 2024-02-10 18:35 UTC
### Describe the improvement

On channel with auto-thread creation behavior enabled allow to override it when message starts/contains some specific marker.
For example having it convigured for messages starting with `!` it would not get auto thread created when posted `! test message`

**Comment by MarcusOtter** [comment] 2024-02-10 19:06
Duplicate of #93

**Closed by MarcusOtter** 2024-02-10 19:06 UTC
Labels: improvement 💡
