### ISSUE TITLE
🐛 setting permissions at the server doesn't affect permissions for a channel

### ISSUE THREAD

**Issue by theparthacus** [MarcusOtter/discord-needle#484] opened 2024-05-07 13:17 UTC
### Describe the bug

the way Discord works, if you choose `Server default` by `/`, whatever permissions are set at the server level then get borrowed into the channel. that doesn't happen with Needle. it keeps throwing a persistent `Needle does not have permission to create threads in this channel` message.

### Steps to reproduce the bug

1. set necessary permissions like `Send messages` and `Send messages in threads` amongst others for Needle at the server.
2. go to `Edit channel` and click `+` to add `Needle` as a member to the channel.
3. choose `/` for the same permissions you set in 1.
4. come back to the channel and type `/auto-thread`, choose operators you want for the channel, and send the message.

    ![Does not have permission to create threads in this channel • Needle](https://github.com/MarcusOtter/discord-needle/assets/108609845/4692bba4-c843-4812-b381-a6c2977ef506)

### Expected behavior

Needle should read permissions from the server and act accordingly in a channel.

**Comment by MarcusOtter** [comment] 2024-05-07 21:50
I am not able to reproduce this.

1. Invite Needle to a completely fresh server, giving no permissions
  ![image](https://github.com/MarcusOtter/discord-needle/assets/35617441/fa9dd620-7f89-4db7-8ac2-dfc047f41c54)
2. Create role "Needle role" with the following permissions:
	  - View channels
	  - Send messages
	  - Send messages in Threads
	  - Create public threads
	  - Read message history
3. Assign this role to Needle
4. In #general (the only text channel), edit the channel permissions to add Needle, changing nothing (leaving everything at `/`)
  ![image](https://github.com/MarcusOtter/discord-needle/assets/35617441/08b91778-da6a-47c6-b723-188f4433c2db)
5. Write `/auto-thread`
6. ![image](https://github.com/MarcusOtter/discord-needle/assets/35617441/d6895dd9-96ab-43cc-aa07-a2999cb0a75e)

Based on the error message, you are missing the `Create public threads` permission.

**Closed** 2024-05-08 06:31 UTC
Labels: potential bug 🐛

**Comment by theparthacus** [comment] 2024-05-08 12:08
this entire thing has to be clearer, in my opinion. there is no way to know a separate role for Needle is the recommended way to get it to work.

**Comment by MarcusOtter** [comment] 2024-05-08 15:42
Open to suggestions!
