### ISSUE TITLE
💡 Translation system

### ISSUE THREAD

**Issue by ravenastar-js** [MarcusOtter/discord-needle#505] opened 2024-12-26 16:02 UTC
### Describe the improvement

I would like to suggest implementing a feature that allows commands to be translated into the user's preferred language.

To facilitate the translation process, command information can be stored in "JSON" files. In these files, the command texts would be listed along with their respective identifiers, allowing easy reference and modification as needed.

This feature can be implemented either in the bot's source code or in a "presets" dashboard created by users, without relying on their own implementation, making the solution more dynamic and flexible.

<details>
<summary>Example</summary>

`translation.json`
```json
{
    "pt_br": {
        "help": {
            "msg_1": "description",
            "msg_2": "description",
            "msg_3": "description",
            "msg_err": "description"
        },
        "auto-thread": {
            "msg_1": "description",
            "msg_2": "description",
            "msg_3": "description",
            "msg_err": "description"
        }
    },
    "en": {
        "help": {
            "msg_1": "description",
            "msg_2": "description",
            "msg_3": "description",
            "msg_err": "description"
        },
        "auto-thread": {
            "msg_1": "description",
            "msg_2": "description",
            "msg_3": "description",
            "msg_err": "description"
        }
    }
}
```
</details>

**Comment by MarcusOtter** [comment] 2024-12-26 16:18
Yes I would love to do this one day

Duplicate of #103

**Closed by MarcusOtter** 2024-12-26 16:18 UTC
Labels: improvement 💡
