### ISSUE TITLE
🐛 configure message update error

### ISSUE THREAD

**Issue by philipaarseth** [MarcusOtter/discord-needle#99] opened 2022-03-05 19:26 UTC
### Describe the bug

Trying to use /message configure on thread create and archive immediately and it will not accept the new string. Instead all that happens is it removes the `$USER` from the default string.

![image](https://user-images.githubusercontent.com/31098164/156897318-b42c019f-c888-4db0-bede-60156143343f.jpeg)

### Steps to reproduce the bug

/configure message key: SUCCESS_THREAD_CREATE value: something

### Expected behavior

The message should update when triggering again.

**Comment by MarcusOtter** [comment] 2022-03-05 23:26
The username going missing is a duplicate of https://github.com/MarcusOtter/discord-needle/issues/60, and this issue may be a duplicate of #60 in general.

I could not reproduce:
![image](https://user-images.githubusercontent.com/35617441/156903028-899f012a-2745-4302-b183-fabb231c1637.png)

**Comment by MarcusOtter** [comment] 2022-03-05 23:26
Could you try again and see if it was just a random failure caused by #60?

**Comment by philipaarseth** [comment] 2022-03-07 12:12
![Screenshot 2022-03-07 at 13 07 21](https://user-images.githubusercontent.com/31098164/157031605-f22be80f-30a9-43c7-ac9c-db5b17aed5ab.jpg)
![Screenshot 2022-03-07 at 13 07 09](https://user-images.githubusercontent.com/31098164/157031611-58b43977-de67-4aaf-8e3b-89005e9e2618.jpg)

Well I'm not trying to use `$USER` in my messages, so may not be related.

I tried 6 different times, the 2 times changing thread close immediately worked but all the ones on thread create did not work.

**Comment by MarcusOtter** [comment] 2022-04-07 13:08
Hi, do you still get this happening now that `v2.1.0` has been released and #60 has been fully fixed? I still cannot reproduce this.

**Comment by philipaarseth** [comment] 2022-04-07 16:17
I'm not sure if this is a new option or not, but I noticed there's a new option "custom-message" on /configure auto-threading which works to change the message 👍

/configure message key: SUCCESS_THREAD_CREATE value: something 
still does not do anything.

**Comment by MarcusOtter** [comment] 2022-04-07 19:50
Ah yeah, since we'll be replacing message customization eventually I'll close this issue for now (even though this bug probably exsists) since people should use the `custom-message` parameter like you mentioned 👍 Thanks!

**Closed by MarcusOtter** 2022-04-07 19:50 UTC
Labels: potential bug 🐛
