### ISSUE TITLE
💡 Only for images or text messages

### ISSUE THREAD

**Issue by Zarthus** [MarcusOtter/discord-needle#229] opened 2022-07-19 13:16 UTC
### Describe the improvement

In some channels, it might make sense to only create a thread when someone posts an image (or a text message, and not on an image)

use cases: 

- I have a bug report channel and I only want to create threads when the user uploads a photo of their bug report, otherwise delete the message

- I have a memes channel and want to keep it image-only, with discussions inside threads.

- I don't want threads on images in an otherwise text-intensive channel

### Alternative solutions

Discord permissions do not allow a photo-only channel without enabling text-send permission as well :(

**Comment by Zarthus** [comment] 2022-07-19 13:20
Looks like a dupe of https://github.com/MarcusOtter/discord-needle/issues/93 actually

**Comment by MarcusOtter** [comment] 2022-07-19 15:52
Duplicate of #93

**Closed as not planned by MarcusOtter** 2022-07-19 15:52 UTC
Labels: duplicate 👉, improvement 💡
