### ISSUE TITLE
💡 Option to only auto-thread messages with images

### ISSUE THREAD

**Issue by Junebugging** [MarcusOtter/discord-needle#447] opened 2023-07-02 21:22 UTC
### Describe the improvement

I'd like to only create threads for messages in a channel that contain images.
This would be an option in /auto-thread, like `message-type` =*only create threads for this type of message*= `image` / `text` / `attachment` / `link`, something like that. Or just just an `only-images` toggle

### Problems this improvement solves

In my server there are a lot of channels, and so there's only one image channel. A lot of people post good pictures in this channel, but they quickly get drowned out by text. Pinning each and every picture isn't an option.
I'd like to keep the conversation centralized in this one channel without creating a splinter channel people would have to hop into to discuss the posted images, so an auto-threading bot is the best choice.

The problem is that I only want threads created for messages that have images in them, for people to discuss the specific images, not for every message posted.

**Comment by MarcusOtter** [comment] 2023-07-02 21:23
Duplicate of #93

**Closed by MarcusOtter** 2023-07-02 21:23 UTC
Labels: improvement 💡
