### ISSUE TITLE
Photo Mode💡 

### ISSUE THREAD

**Issue by frazz1234** [MarcusOtter/discord-needle#210] opened 2022-06-30 15:49 UTC
### Describe the improvement

So, a photo mode create a thread on a picture in the channel.

This improvement will make the channel discord only a photo channel, so if the pers post a thing whitout attachement it will be deleted.

**Comment by MarcusOtter** [comment] 2022-06-30 15:52
Duplicate of #93

**Closed by MarcusOtter** 2022-06-30 15:52 UTC
Labels: improvement 💡
