### ISSUE TITLE
💡 Create threads with buttons and modals

### ISSUE THREAD

**Issue by ririko5834** [MarcusOtter/discord-needle#205] opened 2022-06-24 11:05 UTC
### Describe the improvement

Add support for Discord modals and staff can add questions that will appear on the modal and then select channel where embed with button "Create thread" will be sent. When user clicks on the button, open thread for them and send embed for discord modal responses. This is good when you want to have organized (templated) support on your Discord, its similar to Github forms.

I mean something like this: (its on railway.app Discord support server)
https://i.imgur.com/NbPBI7n.png
https://i.imgur.com/5MElUzS.png

**Comment by MarcusOtter** [comment] 2022-06-30 12:13
In large, this sounds like a duplicate of an issue you opened previously, just with modals this time: https://github.com/MarcusOtter/discord-needle/issues/48

I still think it's slightly out of scope, but I'm also considering this more now as forums will come soon, hopefully replacing the main functionality of Needle. Then this could potentielly be our new primary feature.

**Comment by MarcusOtter** [comment] 2022-09-29 21:55
As Needle is still being used for its primary purpose (auto-threading) a month after forums have been released, I won't be changing the core functionality of Needle or adding any features that don't directly relate to auto-threading. Would be cool if there was a separate bot for this :)

Duplicate of #48

**Closed by MarcusOtter** 2022-09-29 21:55 UTC
Labels: improvement 💡
