### ISSUE TITLE
💡 Add tag (pre-defined messages) system

### ISSUE THREAD

**Issue by ririko5834** [MarcusOtter/discord-needle#66] opened 2022-02-04 11:11 UTC
It would be nice if you would add tag system, that staff can create tags (pre-defined messages) using commands.  The tags should be saved to guild json config file. After tag was created choice option for `/tag name:` should be registered for slash commands for the guild.
Then users (or staff) can use the tag slash commands where will be name option that will include choices of tags for the server.

It will be useful that staff (or users) doesn't have to type the same answers again and again. Pre-defined messages will solve this problem.

**Comment by MarcusOtter** [comment] 2022-02-04 12:22
This seems like a duplicate of #24, could you confirm if that is the same issue?

**Comment by ririko5834** [comment] 2022-02-04 13:02
It's not the same. The other issue is about adding something like Github labels, which I like too.

**Comment by ririko5834** [comment] 2022-02-04 13:03
This one is that staff could set pre-defined messages and then it could be used just by running slash command without having to type the same message again and again. Useful for frequently asked questions or so.

**Comment by MarcusOtter** [comment] 2022-02-04 13:16
So it doesn't really have anything to do with threads, it's more about storing messages that you can send through the bot with a command?

**Comment by ririko5834** [comment] 2022-02-04 14:23
Something like that

**Comment by MarcusOtter** [comment] 2022-02-04 15:03
That seems a bit out of the scope for this bot. I generally dislike "one-size-fits-all" bots and multipurpose bots. There should be a specific bots for this sort of stuff, and Needle is not it.

**Closed by MarcusOtter** 2022-02-04 15:03 UTC
Labels: improvement 💡, out of scope 🤹

**Comment by ririko5834** [comment] 2022-02-04 15:05
I prefer to have one-bot-for-everything, not one bot for tags, second for moderation, next for threads, next for watching threads (unarchiving, at least this should be included), next for tickets, next for music, ...

**Comment by ririko5834** [comment] 2022-02-04 15:06
The problem is that when you have some tag bot and use use command inside thread, the bot won't get it when it's not in the thread. And needle cant add custom bot to threads by default when its created

**Comment by MarcusOtter** [comment] 2022-02-04 15:10
> The problem is that when you have some tag bot and use use command inside thread, the bot won't get it when it's not in the thread

Bots can reply to slash commands even if they are not in the thread.

> And needle cant add custom bot to threads by default when its created
Yes, it can ping it in if you use a custom message for the auto-thread. Users can also just ping the bot into the thread manually.

**Comment by ririko5834** [comment] 2022-02-04 15:37
But my tag bot does not support slash
I also have problem when I have more bots on my server with slash, I type /help and I can't see all bots there. Only some of the,.
Discord should add scroller there if more commands with same name are there.

**Comment by MarcusOtter** [comment] 2022-02-04 19:11
> But my tag bot does not support slash

All verified bots have to be using slash commands soon (april?).

> Discord should add scroller there if more commands with same name are there

I agree that Discord's UI can be better, but that's not anything we can do anything about unfortunately 😅 Also, both on phone and desktop you can filter per-bot

**Comment by MarcusOtter** [comment] 2022-02-04 19:13
> I prefer to have one-bot-for-everything

I'm sorry but Needle will not be this one-for-everything bot, and that will not change. Anyone is free to fork Needle and turn it into that, however. But this fork will not :)

**Comment by ririko5834** [comment] 2022-02-05 08:32
Ok I understand

**Comment by ririko5834** [comment] 2022-02-05 08:33
When it's bot for threads, why you can't add option to watch threads (and prevent them from getting archived)

**Comment by MarcusOtter** [comment] 2022-02-05 12:58
Haha I do like the idea of perma-threads actually, @ririko5834 

I don't know if Discord will like it as much (since thread archive duration longer than 24h is a paid feature). But maybe they don't care. I'll add an issue about this
