### ISSUE TITLE
💡 

### ISSUE THREAD

**Issue by mnkrome** [MarcusOtter/discord-needle#253] opened 2022-08-13 11:31 UTC
### Describe the improvement

Auto delete threads when the original message is deleted.

### Problems this improvement solves

This could help to combine bot for suggestions that doesn't use commands, instead they just resends (and deletes the original) message.

**Comment by MarcusOtter** [comment] 2022-08-13 11:33
Duplicate of #68

**Closed by MarcusOtter** 2022-08-13 11:33 UTC
Labels: improvement 💡
